user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 4096;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    include /etc/nginx/conf.d/*.conf;

    # HTTP Server Block
    # server {
        # listen 80;
        # server_name coca-word.online www.coca-word.online;  # 更新为新的域名

        # 强制重定向 HTTP 到 HTTPS
        # return 301 https://$host$request_uri;
   #}
   
   # HTTP Server Block
	#server {
		#listen 80;
		#server_name www.coca-word.online;
		# 强制重定向到 https://www.coca-word.online
		#return 301 https://coca-word.online$request_uri;
	#}
	
    # HTTPS Server Block
    server {
        listen 443 ssl;
        server_name coca-word.online;   #更新为新的域名

        ssl_certificate /etc/letsencrypt/live/coca-word.online/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/coca-word.online/privkey.pem;

        # SSL 设置
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:...';  # 填写合适的加密套件
        ssl_prefer_server_ciphers on;

        # 强制使用 SSL
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # Angular 应用的根目录
        location / {
            root /var/www/my-angular-app/dist;  # 确保这个路径是 Angular 构建的输出路径
            index index.html;
            try_files $uri $uri/ /index.html;  # 确保 Angular 路由处理（单页应用）

            # CORS 配置
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        }
		
		 location /money {  # 注意这里加了斜杠，确保匹配一致
			alias /var/www/money/dist;       # 使用 alias，确保路径正确映射
			index index.html;
			try_files $uri $uri/ /money/index.html; # 支持 money 项目的单页路由
			# CORS 配置
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		}
		
		location /api/ {
			proxy_pass http://114.132.201.185:8080/;  # HTTP 后端服务
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}
		location = /sogousiteverification.txt {
		    root /var/www/my-angular-app/dist;
			allow all;
		}
		location = /9cfeb4537c1d8a14ef249972e09d62f1.txt {
		    root /var/www/my-angular-app/dist;
			allow all;
		}
		location = /baidu_verify_codeva-NbDa6VuYAq.html {
		    root /var/www/my-angular-app/dist;
			allow all;
		}
		
		location = /baidu_verify_codeva-QYzwdGso3y.html {
		    root /var/www/my-angular-app/dist;
			allow all;
		}
		
        # 错误页面
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }

        # 其他可能需要的配置...
    }
}
