spring:
  profiles:
    active: dev
  application:
    name: money_backend
# 日志级别
logging:
  config: classpath:logback-spring-local.xml
  level:
    org.springframework.data.elasticsearch.core: debug
    org.springframework.data.elasticsearch.client.WIRE: TRACE


